### ISSUE TITLE
Update schema on abstract attributes

### ISSUE THREAD

**Issue by germainlefebvre4** [germainlefebvre4/cvwonder#35]
## Description

The schema the CV is malformed on `abstract` attribute. It ocntains unused `tr` Key. Just remove the key to only have a list of strings.

## Example

Before

```yaml
abstract:
  - tr: "First line"
  - tr: "Seconde line"
```

After

```yaml
abstract:
  - "First line"
  - "Seconde line"
```
